### ISSUE TITLE
[Feat] 최종시간 고르기 UI 구현

### ISSUE THREAD

**Issue by green-yoon87** [TeamY-ETA/iOS#20]
# 📝 작업 내용
- 최종시간 고르기 UI 구현

## ✔️ To-Do
- [x] 확인 버튼 구현
- [x] 최종 시간 리스트 구현 
- [x] 각종 라벨 구현
