### ISSUE TITLE
[Feat] Font 및 Color 세팅

### ISSUE THREAD

**Issue by youz2me** [TeamY-ETA/iOS#3]
# 📝 작업 내용
- 피그마 컬러 및 폰트 에셋을 참고해 세팅을 진행합니다.
- `feat/font-color-setting` 브랜치에서 진행합니다.

## ✔️ To-Do
- [ ] Asset 파일에 색 추가
- [ ] Pretendard 폰트 추가
- [ ] FontData 및 ColorData 파일 추가
- [ ] 필요한 Extension 추가

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)
